

height = 2/3;
set(0,...
'defaultfigureposition',[180 100 800 800*height],...
'defaultaxeslinewidth',1,...
'defaultaxesfontsize',18,...
'defaultaxesfontname','Arial',...
'defaultlinelinewidth',2,...
'defaultpatchlinewidth',1,...
'defaultlinemarkersize',10,...
'defaulttextinterpreter','tex');


